# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-25 15:09
from __future__ import unicode_literals

import dc_user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, default='head/user.png', null=True, storage=dc_user.utils.ImageStorage(), upload_to='head/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='指明用户是否被认为活跃的。以反选代替删除帐号。', verbose_name='有效'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='指明用户是否可以登录到这个管理站点。', verbose_name='职员状态'),
        ),
    ]
