# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmen',
            name='serial_num',
            field=models.CharField(max_length=128, verbose_name='设备SN号'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmen',
            unique_together=set([('cabinet', 'serial_num')]),
        ),
    ]
