# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc_info', '0002_auto_20180311_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmen',
            name='up_date',
            field=models.DateField(blank=True, null=True, verbose_name='上架日期'),
        ),
    ]
